name: approve
on:
  workflow_dispatch

jobs:
  approve:
    name: approve
    runs-on: ubuntu-latest
    steps:
      - uses: ToshihitoKon/slack-quickpost@v1
        with:
          version: 0.7.1

      - name: Check unauthorized users
        if: github.triggering_actor != "ToshihitoKon"
        run: exit 1

      - name: Approve
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          slack-quickpost \
            --token ${{ secrets.SLACK_TOKEN }} \
            --channel ${{ secrets.SLACK_CHANNEL }} \
            --username "GitHub Actions: ${{ github.workflow }}" \
            --text ":white_check_mark: Approved by ${{ github.triggering_actor }}"
